-- MySQL Script generated by MySQL Workbench
-- Thu Jun 19 10:02:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema new_technology_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_technology_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_technology_db` DEFAULT CHARACTER SET utf8 ;
USE `new_technology_db` ;

-- -----------------------------------------------------
-- Table `new_technology_db`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_technology_db`.`Products` (
  `idProducts` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ProductType` VARCHAR(100) NOT NULL,
  `NameOfProduct` TEXT NOT NULL,
  `ArtikulOfProduct` INT(7) NOT NULL,
  `MinPriceOfProduct` VARCHAR(20) NOT NULL,
  UNIQUE INDEX `idProducts_UNIQUE` (`idProducts` ASC) VISIBLE,
  PRIMARY KEY (`idProducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_technology_db`.`ProductType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_technology_db`.`ProductType` (
  `idProductType` INT NOT NULL AUTO_INCREMENT,
  `ProductType` VARCHAR(100) NOT NULL,
  `ProductTypePercent` VARCHAR(10) NOT NULL,
  UNIQUE INDEX `idProductType_UNIQUE` (`idProductType` ASC) VISIBLE,
  PRIMARY KEY (`idProductType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_technology_db`.`Partners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_technology_db`.`Partners` (
  `idPartners` INT NOT NULL AUTO_INCREMENT,
  `TypeOfPartner` VARCHAR(3) NOT NULL,
  `NameOfPartner` VARCHAR(100) NOT NULL,
  `DirectorOfPartner` VARCHAR(100) NOT NULL,
  `EmailOfPartner` VARCHAR(100) NOT NULL,
  `TelephoneOfPartner` VARCHAR(13) NOT NULL,
  `AddressOfPartner` TEXT NOT NULL,
  `INNOfPartner` BIGINT(10) NOT NULL,
  `RatingOfPartner` INT NOT NULL,
  UNIQUE INDEX `idPartners_UNIQUE` (`idPartners` ASC) VISIBLE,
  PRIMARY KEY (`idPartners`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_technology_db`.`Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_technology_db`.`Request` (
  `idRequest` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NameOfProduct` TEXT NOT NULL,
  `NameOfPartner` VARCHAR(100) NOT NULL,
  `RequestNumber` INT NOT NULL,
  PRIMARY KEY (`idRequest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_technology_db`.`MaterialType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_technology_db`.`MaterialType` (
  `idMaterialType` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(100) NOT NULL,
  `PercentOfBrak` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idMaterialType`),
  UNIQUE INDEX `idMaterialType_UNIQUE` (`idMaterialType` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
